{% set version = "2.6.2" %}

package:
  name: magma
  version: {{ version }}

source:
  url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
  sha256: ff49ee0b07ab20205667b5af08615b80406c05a2a9a5b5e4c65bcfee8759a6d0
  patches:
    - cmakelists.patch
    - thread_queue.patch
    - dllexport.patch
    - fix_macro_win.patch
    - option_to_disable_sparse.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version=="None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [unix]
    - jom  # [win]
    - libgomp  # [linux]
    - llvm-openmp  # [osx or win]
    - m2-sed  # [win]
  host:
    - liblapack
    - libblas

test:
  commands:
    - test -f $PREFIX/include/magma.h  # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1  # [win]

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - isuruf
