{% set version = "2.7.0" %}

package:
  name: magma
  version: {{ version }}

source:
  url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
  sha256: 22bc15f6c65b20e2f57d6000b93313f8f41e6b341c82de54f072d35e5c52ca01
  patches:
    - cmakelists.patch
    - thread_queue.patch
    - dllexport.patch
    - fix_macro_win.patch
    - option_to_disable_sparse.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version=="None"]
  run_exports:
    - {{ pin_subpackage('magma', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
    - libgomp  # [linux]
    - llvm-openmp  # [osx or win]
    - m2-sed  # [win]
  host:
    - liblapack
    - libblas

test:
  commands:
    - test -f $PREFIX/include/magma.h  # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}   # [unix]
    - test -f $PREFIX/lib/libmagma_sparse${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma.dll exit 1  # [win]

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - carterbox
    - conda-forge/pytorch-cpu
