{% set version = "2.5.4" %}

package:
  name: magma
  version: {{ version }}

source:
  url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
  sha256: 7734fb417ae0c367b418dea15096aef2e278a423e527c615aab47f0683683b67
  patches:
    - cmakelists.patch
    - thread_queue.patch

build:
  number: 1
  skip: true  # [not (linux64 or win) or cuda_compiler_version=="None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [unix]
    - jom  # [win]
    - libgomp  # [linux]
    - llvm-openmp  # [osx or win]
    - m2-sed  # [win]
  host:
    - liblapack
    - libblas

test:
  commands:
    - test -f $PREFIX/include/magma.h  # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\libmagma.lib exit 1  # [win]

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - isuruf
